import Head from "next/head";
import { Canvas } from '@react-three/fiber'
import { OrbitControls } from '@react-three/drei'
import StartAgainExperience from "~/components/Experiences/StartAgainExperience";


export default function StartAgain() {
  return (
    <>
      <Head>
        <title>Start Again</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-touch-fullscreen" content="yes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="main">
        <Canvas
          shadows
          camera={{
            fov: 75,
            near: 0.01,
            far: 1000,
            position: [0, 12, 12]
          }}
        >
          <OrbitControls />
          <StartAgainExperience />
        </Canvas>
      </main>
    </>
  );
}